---
# just build

kind: pipeline
name: unit

steps:
- name: monorepo
  image: golang:1.18.3
  environment:
    CGO_ENABLED: false
    GOPROXY: "http://10.254.253.1:8888"
  commands:
    - echo "Running netflow tests"
    - go test github.com/gravwell/gravwell/v3/netflow
    - echo "Running ipexist tests"
    - go test github.com/gravwell/gravwell/v3/ipexist
    - echo "Running ingesters tests"
    - go test github.com/gravwell/gravwell/v3/ingesters/utils
    - go test github.com/gravwell/gravwell/v3/ingesters/kafka_consumer
    - go test github.com/gravwell/gravwell/v3/ingesters/SimpleRelay
    - go test github.com/gravwell/gravwell/v3/ingesters/utils
    - echo "Running timegrinder tests"
    - go test github.com/gravwell/gravwell/v3/timegrinder
    - echo "Running filewatch tests"
    - go test github.com/gravwell/gravwell/v3/filewatch
    - echo "Running processors tests"
    - go test github.com/gravwell/gravwell/v3/ingest/processors
    - go test github.com/gravwell/gravwell/v3/ingest/processors/plugin
    - echo "Running ingest tests"
    - go test github.com/gravwell/gravwell/v3/ingest
    - go test github.com/gravwell/gravwell/v3/ingest/config
    - go test github.com/gravwell/gravwell/v3/ingest/entry
    - echo "Running cache tests"
    - go test github.com/gravwell/gravwell/v3/chancacher
    - echo "Running generators tests"
    - go test github.com/gravwell/gravwell/v3/generators/ipgen
    - echo "Running client tests"
    - go test github.com/gravwell/gravwell/v3/client
    - go test github.com/gravwell/gravwell/v3/client/types

node:
  host: neutest

---

kind: pipeline
name: build

steps:
- name: corebuild
  image: golang:1.18.3
  environment:
    GOMAXPROCS: 4
    CGO_ENABLED: false
    GOPROXY: "http://10.254.253.1:8888"
  volumes:
    - name: shm
      path: /dev/shm
  commands:
  - echo 'Acquire::http { Proxy "http://10.254.253.1:3142"; };' > /etc/apt/apt.conf.d/01aptproxy
  - VER="5.0.5"
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/SimpleRelay -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/GooglePubSubIngester -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/massFile -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/diskmonitor -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/HttpIngester -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/collectd -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/xlsxIngester -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/netflow -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/KinesisIngester -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/reimport -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/kafka_consumer -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/fileFollow -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/canbus -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/reddit_ingester -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/hackernews_ingester -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/singleFile -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/sqsIngester -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/multiFile -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/session -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/regexFile -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/pcapFileIngester -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/SimpleRelay -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/O365Ingester -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/PacketFleet -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/MSGraphIngester -version | awk '$1~"Version"{print $2}') = $VER
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/IPMIIngester -version | awk '$1~"Version"{print $2}') = $VER
  - GOOS=windows go build -o /dev/shm/tempbin github.com/gravwell/gravwell/v3/ingesters/winevents
  - GOOS=windows go build -o /dev/shm/tempbin github.com/gravwell/gravwell/v3/ingesters/fileFollow
  - apt update
  - apt install -y libpcap-dev
  - test $(go run github.com/gravwell/gravwell/v3/ingesters/networkLog -version | awk '$1~"Version"{print $2}') = $VER

volumes:
  - name: shm
    temp: {}

trigger:
  event:
    - pull_request

node:
  host: neutest
---
kind: signature
hmac: e358aa6ec6061b72ad18be530ab15859e7b94e06f5900a15890d8cb8a16fbb6f

...
